goog.provide("google.ads.adwords.objstatsext.AwApiLoader");goog.require("google.ads.adwords.v201008.CampaignSelector");goog.require("google.ads.adwords.v201008.CampaignService");goog.require("google.system.net.HttpWebTransportForExtensions");goog.require("google.ads.adwords.User");
google.ads.adwords.objstatsext.AwApiLoader=function(config,statsStartDate,statsEndDate){this.CAMPAIGNS_CACHE_KEY="cm";this.AD_GROUPS_CACHE_KEY="ag";this.ADS_CACHE_KEY="ad";this.CRITERIA_CACHE_KEY="cr";if(config)this.setConfig(config);this.statsStartDate=statsStartDate;this.statsEndDate=statsEndDate;this.cache_=new google.ads.adwords.objstatsext.AwApiCache};
google.ads.adwords.objstatsext.AwApiLoader.prototype.setConfig=function(config){this.awapiConfig=new google.ads.adwords.AppConfig;var settings={Email:config.email,Password:config.password,DeveloperToken:config.developerToken,HttpWebTransport:"google.system.net.HttpWebTransportForExtensions"};if(config.clientId.indexOf("@")>=0)settings.ClientEmail=config.clientId;else settings.ClientCustomerId=config.clientId;this.awapiConfig.readSettings(settings);this.user=new google.ads.adwords.User(this.awapiConfig)};
google.ads.adwords.objstatsext.AwApiLoader.prototype.formatAPIDate_=function(date){return $.datepicker.formatDate("yymmdd",date)};google.ads.adwords.objstatsext.AwApiLoader.prototype.constructDateRange_=function(){var dateRange=new google.ads.adwords.v201008.DateRange;dateRange.min=this.formatAPIDate_(this.statsStartDate);dateRange.max=this.formatAPIDate_(this.statsEndDate);return dateRange};
google.ads.adwords.objstatsext.AwApiLoader.prototype.constructPaging_=function(offset,numberResults){var paging=new google.ads.adwords.v201008.Paging;paging.startIndex=offset;paging.numberResults=numberResults;return paging};google.ads.adwords.objstatsext.AwApiLoader.prototype.formatMoney_=function(money){return Math.round(money.microAmount/1E4)/100};google.ads.adwords.objstatsext.AwApiLoader.prototype.formatDecimal_=function(value){return Math.round(value*100)/100};
google.ads.adwords.objstatsext.AwApiLoader.prototype.getCampaign=function(campaignId,callback,errorCallback){this.getCampaigns(this.campaignsLastRequestParameters_.offset,this.campaignsLastRequestParameters_.numberResults,goog.bind(function(page){if(page&&page.entries)for(var i=0,len=page.entries.length;i<len;i++)if(page.entries[i].id==campaignId)return callback(page.entries[i]);callback(null)},this),errorCallback)};
google.ads.adwords.objstatsext.AwApiLoader.prototype.getCampaigns=function(offset,numberResults,callback,errorCallback){var cacheKey=this.CAMPAIGNS_CACHE_KEY+"-"+this.statsStartDate.getTime()+"-"+this.statsEndDate.getTime()+"-"+offset+"-"+numberResults;var cachedResults=this.cache_.getObject(cacheKey);if(cachedResults){callback(cachedResults);return}this.campaignsLastRequestParameters_={offset:offset,numberResults:numberResults};var campaignService=this.user.getService(google.ads.adwords.AdWordsService.v201008.CampaignService);
var selector=new google.ads.adwords.v201008.CampaignSelector;selector.campaignStatuses=[google.ads.adwords.v201008.CampaignStatus.ACTIVE,google.ads.adwords.v201008.CampaignStatus.PAUSED];selector.statsSelector=new google.ads.adwords.v201008.StatsSelector;selector.statsSelector.dateRange=this.constructDateRange_();selector.paging=this.constructPaging_(offset,numberResults);campaignService.get(selector,goog.bind(function(results){if(results.entries)results.entries.forEach(goog.bind(function(campaign){campaign.budget.amount.value=
this.formatMoney_(campaign.budget.amount);campaign.campaignStats.cost.value=this.formatMoney_(campaign.campaignStats.cost)},this));else results.entries=[];this.cache_.setObject(cacheKey,results);callback(results)},this),goog.bind(function(exception){errorCallback(exception)},this))};
google.ads.adwords.objstatsext.AwApiLoader.prototype.getAdGroup=function(adGroupId,callback,errorCallback){this.getAdGroups(this.adGroupsLastRequestParameters_.campaignId,this.adGroupsLastRequestParameters_.offset,this.adGroupsLastRequestParameters_.numberResults,goog.bind(function(page){if(page&&page.entries)for(var i=0,len=page.entries.length;i<len;i++)if(page.entries[i].id==adGroupId)return callback(page.entries[i]);callback(null)},this),errorCallback)};
google.ads.adwords.objstatsext.AwApiLoader.prototype.getAdGroups=function(campaignId,offset,numberResults,callback,errorCallback){var cacheKey=this.AD_GROUPS_CACHE_KEY+"-"+this.statsStartDate.getTime()+"-"+this.statsEndDate.getTime()+"-"+campaignId+"-"+offset+"-"+numberResults;var cachedResults=this.cache_.getObject(cacheKey);if(cachedResults){callback(cachedResults);return}this.adGroupsLastRequestParameters_={offset:offset,numberResults:numberResults,campaignId:campaignId};var adGroupService=this.user.getService(google.ads.adwords.AdWordsService.v201008.AdGroupService);
var selector=new google.ads.adwords.v201008.AdGroupSelector;selector.adGroupStatuses=[google.ads.adwords.v201008.AdGroupStatus.ENABLED,google.ads.adwords.v201008.AdGroupStatus.PAUSED];selector.campaignIds=[campaignId];selector.statsSelector=new google.ads.adwords.v201008.StatsSelector;selector.statsSelector.dateRange=this.constructDateRange_();selector.paging=this.constructPaging_(offset,numberResults);adGroupService.get(selector,goog.bind(function(results){if(results.entries){results.entries.forEach(goog.bind(function(adGroup){switch(adGroup.bids.adGroupBidsType){case "ManualCPMAdGroupBids":adGroup.bid=
this.formatMoney_(adGroup.bids.maxCpm.amount);break;case "ManualCPCAdGroupBids":adGroup.bid=this.formatMoney_(adGroup.bids.keywordMaxCpc.amount);break;default:adGroup.bid="NA"}adGroup.stats.cost.value=this.formatMoney_(adGroup.stats.cost);adGroup.stats.averagePosition=this.formatDecimal_(adGroup.stats.averagePosition)},this));this.cache_.setObject(cacheKey,results)}else results.entries=[];callback(results)},this),goog.bind(function(exception){errorCallback(exception)},this))};
google.ads.adwords.objstatsext.AwApiLoader.prototype.getAds=function(adGroupId,offset,numberResults,callback,errorCallback){var cacheKey=this.ADS_CACHE_KEY+"-"+this.statsStartDate.getTime()+"-"+this.statsEndDate.getTime()+"-"+adGroupId+"-"+offset+"-"+numberResults;var cachedResults=this.cache_.getObject(cacheKey);if(cachedResults){callback(cachedResults);return}this.adsLastRequestParameters_={offset:offset,numberResults:numberResults,adGroupId:adGroupId};var adGroupAdService=this.user.getService(google.ads.adwords.AdWordsService.v201008.AdGroupAdService);
var selector=new google.ads.adwords.v201008.AdGroupAdSelector;selector.adGroupStatuses=[google.ads.adwords.v201008.AdGroupAdStatus.ENABLED,google.ads.adwords.v201008.AdGroupAdStatus.PAUSED];selector.adGroupIds=[adGroupId];selector.statsSelector=new google.ads.adwords.v201008.StatsSelector;selector.statsSelector.dateRange=this.constructDateRange_();selector.paging=this.constructPaging_(offset,numberResults);adGroupAdService.get(selector,goog.bind(function(results){if(results.entries){results.entries.forEach(goog.bind(function(adGroupAd){adGroupAd.typeTitle=
adGroupAd.ad.adType;switch(adGroupAd.ad.adType){case "TextAd":adGroupAd.typeTitle+=" / "+adGroupAd.ad.headline;break;case "ProductAd":adGroupAd.typeTitle+=" / "+adGroupAd.ad.promotionLine;break;case "MobileAd":adGroupAd.typeTitle+=" / "+adGroupAd.ad.headline;break;case "RichMediaAd":adGroupAd.typeTitle+=" / "+adGroupAd.ad.name;break;case "ImageAd":adGroupAd.typeTitle+=" / "+adGroupAd.ad.name;break;case "LocalBusinessAd":adGroupAd.typeTitle+=" / "+adGroupAd.ad.fullBusinessName;break;case "TemplateAd":adGroupAd.typeTitle+=
" / "+adGroupAd.ad.name;break}adGroupAd.stats.cost.value=this.formatMoney_(adGroupAd.stats.cost);adGroupAd.stats.averagePosition=this.formatDecimal_(adGroupAd.stats.averagePosition)},this));this.cache_.setObject(cacheKey,results)}else results.entries=[];callback(results)},this),goog.bind(function(exception){errorCallback(exception)},this))};
google.ads.adwords.objstatsext.AwApiLoader.prototype.getCriteria=function(adGroupId,offset,numberResults,callback,errorCallback){var cacheKey=this.CRITERIA_CACHE_KEY+"-"+this.statsStartDate.getTime()+"-"+this.statsEndDate.getTime()+"-"+adGroupId+"-"+offset+"-"+numberResults;var cachedResults=this.cache_.getObject(cacheKey);if(cachedResults){callback(cachedResults);return}this.criteriaLastRequestParameters_={offset:offset,numberResults:numberResults,adGroupId:adGroupId};var criteriaService=this.user.getService(google.ads.adwords.AdWordsService.v201008.AdGroupCriterionService);
var selector=new google.ads.adwords.v201008.AdGroupCriterionSelector;selector.adGroupStatuses=[google.ads.adwords.v201008.AdGroupStatus.ENABLED,google.ads.adwords.v201008.AdGroupStatus.PAUSED];selector.idFilters=[new google.ads.adwords.v201008.AdGroupCriterionIdFilter];selector.criterionUse=google.ads.adwords.v201008.CriterionUse.BIDDABLE;selector.idFilters[0].adGroupId=adGroupId;selector.statsSelector=new google.ads.adwords.v201008.StatsSelector;selector.statsSelector.dateRange=this.constructDateRange_();
selector.paging=this.constructPaging_(offset,numberResults);criteriaService.get(selector,goog.bind(function(results){if(results.entries){results.entries.forEach(goog.bind(function(adGroupCriterion){adGroupCriterion.typeTitle=adGroupCriterion.criterion.criterionType;switch(adGroupCriterion.criterion.criterionType){case "CriterionUserInterest":adGroupCriterion.typeTitle+=" / "+adGroupCriterion.criterion.userInterestName;break;case "CriterionUserList":adGroupCriterion.typeTitle+=" / "+adGroupCriterion.criterion.userListName;
break;case "Keyword":adGroupCriterion.typeTitle+=" / "+adGroupCriterion.criterion.text;break;case "Placement":adGroupCriterion.typeTitle+=" / "+adGroupCriterion.criterion.url;break;case "Product":adGroupCriterion.typeTitle+=" / "+adGroupCriterion.criterion.text;break}switch(adGroupCriterion.bids.adGroupCriterionBidsType){case "BudgetOptimizerAdGroupCriterionBids":adGroupCriterion.bid=this.formatMoney_(adGroupCriterion.bids.proxyBid.amount);break;case "ManualCPMAdGroupCriterionBids":adGroupCriterion.bid=
this.formatMoney_(adGroupCriterion.bids.maxCpm.amount);break;case "ManualCPCAdGroupCriterionBids":adGroupCriterion.bid=this.formatMoney_(adGroupCriterion.bids.maxCpc.amount);break;default:adGroupCriterion.bid="NA"}adGroupCriterion.stats.cost.value=this.formatMoney_(adGroupCriterion.stats.cost);adGroupCriterion.stats.averagePosition=this.formatDecimal_(adGroupCriterion.stats.averagePosition)},this));this.cache_.setObject(cacheKey,results)}else results.entries=[];callback(results)},this),goog.bind(function(exception){errorCallback(exception)},
this))};goog.provide("google.ads.adwords.objstatsext.AwApiCache");google.ads.adwords.objstatsext.AwApiCache=function(cacheSize,entryLifeSpan){this.INVALIDATION_LIFESPAN=cacheSize?cacheSize:300;this.MAX_CACHE_SIZE=entryLifeSpan?entryLifeSpan:50;this.cacheByTime_=[];this.cacheByKey_=[];this.cacheSize_=0};
google.ads.adwords.objstatsext.AwApiCache.prototype.setObject=function(key,object){var cacheEntry={object:object,timestamp:(new Date).getTime(),key:key};this.cacheByTime_.push(cacheEntry);this.cacheByKey_[key]=cacheEntry;this.cacheSize_++;if(this.cacheSize_>this.MAX_CACHE_SIZE)setTimeout(goog.bind(this.cleanCache_(),this),10)};
google.ads.adwords.objstatsext.AwApiCache.prototype.cleanCache_=function(){var toDelete=this.cacheSize_-Math.round(this.MAX_CACHE_SIZE*0.1);for(var i=0;i<toDelete;i++){var cacheEntry=this.cacheByTime_[i];if(cacheEntry){this.cacheByTime_.splice(i,1);var idx=this.cacheByKey_[cacheEntry.key];if(idx>=0)delete this.cacheByKey_[cacheEntry.key];this.cacheSize--}else return}};
google.ads.adwords.objstatsext.AwApiCache.prototype.getObject=function(key){var cacheEntry=this.cacheByKey_[key];if(cacheEntry&&(new Date).getTime()-cacheEntry.timestamp<this.INVALIDATION_LIFESPAN*1E3)return cacheEntry.object;else{var idx=this.cacheByTime_.indexOf(cacheEntry);if(idx>=0){this.cacheByTime_.splice(idx,1);delete this.cacheByKey_[key];this.cacheSize_--}return null}};goog.provide("google.ads.adwords.objstatsext.SettingsLoader");google.ads.adwords.objstatsext.SettingsLoader=function(){};google.ads.adwords.objstatsext.SettingsLoader.prototype.getConfig=function(){return this.getSettings().config};google.ads.adwords.objstatsext.SettingsLoader.prototype.saveConfig=function(config){var setttings=this.getSettings();setttings.config=config;this.saveSettings(setttings)};
google.ads.adwords.objstatsext.SettingsLoader.prototype.getSettings=function(){var settingsJSON=localStorage.getItem("awapi-object-stats");var settings;if(!settingsJSON){settings={config:{email:"",password:"",clientId:"",developerToken:""}};this.saveSettings(settings)}else settings=JSON.parse(settingsJSON);return settings};google.ads.adwords.objstatsext.SettingsLoader.prototype.saveSettings=function(settings){localStorage.setItem("awapi-object-stats",JSON.stringify(settings))};goog.require("google.ads.adwords.objstatsext.AwApiLoader");goog.require("google.ads.adwords.objstatsext.SettingsLoader");goog.provide("google.ads.adwords.objstatsext.UIManager");
google.ads.adwords.objstatsext.UIManager=function(){this.EMAIL_EXPR_=/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.(?:[A-Z]{2}|com|org|net|edu|gov|mil|biz|info|mobi|name|aero|asia|jobs|museum)$/i;this.PER_PAGE_=10;this.STATS_VIEW=0;this.GRAPH_VIEW=1;this.VIEW_ANIMATION_DELAY=500;this.ALL_CAMPAIGNS_VIEW=0;this.CAMPAIGN_VIEW=1;this.AD_GROUP_VIEW=2;this.awApiLoader_=new google.ads.adwords.objstatsext.AwApiLoader;this.settingsLoader=new google.ads.adwords.objstatsext.SettingsLoader;this.toDate=this.getToday_();this.fromDate=
this.getToday_();this.fromDate.setDate(this.toDate.getDate()-7);this.crumbtrailElements_=[{label:"All Campaigns",action:"uiManager.goToAllCampaigns()"}];this.allCampaignsView_={viewName:this.ALL_CAMPAIGNS_VIEW,viewState:this.STATS_VIEW,loading:false,dataTableViews:{campaignsDataTable:{page:1,data:[],resultsTable:"campaignsResult",loadingView:"campaignsLoading",paginationSection:"campaignsPagination",dataRowTemplate:"campaignRowTemplate",countersSection:"allCampaignsCounters",previousLink:"previousCampaigns",
nextLink:"nextCampaigns",dataAdapterGet:goog.bind(this.awApiLoader_.getCampaigns,this.awApiLoader_),graphRenderer:goog.bind(this.renderAllCampaignsGraph_,this)}}};this.campaignView_={viewName:this.CAMPAIGN_VIEW,viewState:this.STATS_VIEW,loading:false,campaign:null,dataTableViews:{adGroupsDataTable:{page:1,data:[],resultsTable:"adGroupsResult",loadingView:"adGroupsLoading",paginationSection:"adGroupsPagination",dataRowTemplate:"adGroupRowTemplate",countersSection:"adGroupsCounters",previousLink:"previousAdGroups",
nextLink:"nextAdGroups",dataAdapterGet:null,graphRenderer:goog.bind(this.renderAdGroupsGraph_,this)}}};this.adGroupView_={viewName:this.AD_GROUP_VIEW,viewState:this.STATS_VIEW,loading:false,adGroup:null,dataTableViews:{adsDataTable:{page:1,data:[],resultsTable:"adsResult",loadingView:"adsLoading",paginationSection:"adsPagination",dataRowTemplate:"adsRowTemplate",countersSection:"adCounters",previousLink:"previousAds",nextLink:"nextAds",dataAdapterGet:null,graphRenderer:goog.bind(this.renderAdsGraph_,
this)},criteriaDataTable:{page:1,data:[],resultsTable:"criteriaResult",loadingView:"criteriaLoading",paginationSection:"criteriaPagination",dataRowTemplate:"criteriaRowTemplate",countersSection:"criteriaCounters",previousLink:"previousCriteria",nextLink:"nextCriteria",dataAdapterGet:null,graphRenderer:goog.bind(this.renderCriteriaGraph_,this)}}};this.currentView_=this.allCampaignsView_};
google.ads.adwords.objstatsext.UIManager.prototype.init=function(){$("#adGroupTabs").tabs();$("#fromDate").datepicker({onClose:goog.bind(this.dateChanged_,this)});$("#toDate").datepicker({onClose:goog.bind(this.dateChanged_,this)});$("#fromDate").val(this.formatDate_(this.fromDate));$("#toDate").val(this.formatDate_(this.toDate));this.renderCrumbtrail();if(!this.settingsLoader.getConfig().email){$("#extensionBody").hide();$("#settingsErrorAlert").hide();$("#settingAlerts").show();$("#missingSettingsAlert").show()}else{this.awApiLoader_.setConfig(this.settingsLoader.getConfig());
this.awApiLoader_.statsStartDate=this.fromDate;this.awApiLoader_.statsEndDate=this.toDate;setTimeout(goog.bind(this.renderAllCampaigns_,this),10)}};google.ads.adwords.objstatsext.UIManager.prototype.renderAllCampaigns_=function(){if(this.allCampaignsView_.loading)return;this.switchToStats();this.allCampaignsView_.loading=true;this.updateDataTable_(this.allCampaignsView_,this.allCampaignsView_.dataTableViews.campaignsDataTable)};
google.ads.adwords.objstatsext.UIManager.prototype.renderAllCampaignsGraph_=function(campaigns){if(google.visualization&&google.visualization.DataTable){var data=new google.visualization.DataTable;data.addColumn("string","Campaign");data.addColumn("number","Impressions");data.addColumn("number","Clicks");data.addColumn("number","Conversions");data.addRows(campaigns.length);for(var j=0;j<campaigns.length;++j){data.setValue(j,0,campaigns[j].name);data.setValue(j,1,campaigns[j].campaignStats.impressions);
data.setValue(j,2,campaigns[j].campaignStats.clicks);data.setValue(j,3,campaigns[j].campaignStats.conversions)}(new google.visualization.BarChart(document.getElementById("campaignsGraph"))).draw(data,{title:"Campaign Statistics",width:479,height:330,hAxis:{logScale:true}})}else this.showGraphUnavailableError_(document.getElementById("campaignsGraph"))};google.ads.adwords.objstatsext.UIManager.prototype.nextCampaigns=function(){this.allCampaignsView_.dataTableViews.campaignsDataTable.page++;this.renderAllCampaigns_()};
google.ads.adwords.objstatsext.UIManager.prototype.previousCampaigns=function(){if(this.allCampaignsView_.dataTableViews.campaignsDataTable.page==1)return;this.allCampaignsView_.dataTableViews.campaignsDataTable.page--;this.renderAllCampaigns_()};
google.ads.adwords.objstatsext.UIManager.prototype.goToAllCampaigns=function(){this.crumbtrailElements_=[{label:"All Campaigns",action:"uiManager.goToAllCampaigns()"}];this.renderCrumbtrail();$("#sectionsSlider").clearQueue();$("#sectionsSlider").animate({left:"0px"},this.VIEW_ANIMATION_DELAY);this.currentView_=this.allCampaignsView_;this.renderAllCampaigns_()};
google.ads.adwords.objstatsext.UIManager.prototype.selectCampaign=function(campaignId){$("#sectionsSlider").clearQueue();$("#sectionsSlider").animate({left:"-500px"},this.VIEW_ANIMATION_DELAY);this.pushToCrumbtrail_({label:"Campaign "+campaignId,action:"uiManager.backToCampaign("+campaignId+")"});this.currentView_=this.campaignView_;this.renderCampaign_(campaignId)};
google.ads.adwords.objstatsext.UIManager.prototype.renderCampaign_=function(campaignId){if(this.campaignView_.loading)return;if(!campaignId)if(this.campaignView_.campaign)campaignId=this.campaignView_.campaign.id;else return;this.switchToStats();this.campaignView_.loading=true;this.awApiLoader_.getCampaign(campaignId,goog.bind(function(campaign){this.campaignView_.campaign=campaign;$("#campaignName").html(this.campaignView_.campaign.name);$("#campaignBudget").text(this.campaignView_.campaign.budget.amount.value);
$("#campaignClicks").text(this.campaignView_.campaign.campaignStats.clicks);$("#campaignImpressions").text(this.campaignView_.campaign.campaignStats.impressions);$("#campaignCost").text(this.campaignView_.campaign.campaignStats.cost.value);$("#campaignConversions").text(this.campaignView_.campaign.campaignStats.conversions)},this),goog.bind(this.handleError_,this));this.campaignView_.dataTableViews.adGroupsDataTable.dataAdapterGet=goog.bind(this.awApiLoader_.getAdGroups,this.awApiLoader_,campaignId);
this.updateDataTable_(this.campaignView_,this.campaignView_.dataTableViews.adGroupsDataTable)};
google.ads.adwords.objstatsext.UIManager.prototype.renderAdGroupsGraph_=function(adGroups){if(google.visualization&&google.visualization.DataTable){var data=new google.visualization.DataTable;data.addColumn("string","AdGroup");data.addColumn("number","Imp.");data.addColumn("number","Clicks");data.addColumn("number","Conv.");data.addColumn("number","Cost");data.addColumn("number","Avg. Pos.");data.addRows(adGroups.length);for(var j=0;j<adGroups.length;++j){data.setValue(j,0,adGroups[j].name);data.setValue(j,
1,adGroups[j].stats.impressions);data.setValue(j,2,adGroups[j].stats.clicks);data.setValue(j,3,adGroups[j].stats.conversions);data.setValue(j,4,adGroups[j].stats.cost.value);data.setValue(j,5,adGroups[j].stats.averagePosition)}(new google.visualization.BarChart(document.getElementById("adGroupsGraph"))).draw(data,{title:"Ad Group Statistics",width:479,height:330,hAxis:{logScale:true}})}else this.showGraphUnavailableError_(document.getElementById("adGroupsGraph"))};
google.ads.adwords.objstatsext.UIManager.prototype.nextAdGroups=function(){this.campaignView_.dataTableViews.adGroupsDataTable.page++;this.renderCampaign_()};google.ads.adwords.objstatsext.UIManager.prototype.previousAdGroups=function(){if(this.campaignView_.dataTableViews.adGroupsDataTable.page==1)return;this.campaignView_.dataTableViews.adGroupsDataTable.page--;this.renderCampaign_()};
google.ads.adwords.objstatsext.UIManager.prototype.backToCampaign=function(campaignId){$("#sectionsSlider").clearQueue();$("#sectionsSlider").animate({left:"-500px"},this.VIEW_ANIMATION_DELAY);this.popFromCrumbtrail_();this.currentView_=this.campaignView_;this.renderCampaign_()};
google.ads.adwords.objstatsext.UIManager.prototype.selectAdGroup=function(adGroupId){$("#sectionsSlider").clearQueue();$("#sectionsSlider").animate({left:"-1000px"},this.VIEW_ANIMATION_DELAY);this.pushToCrumbtrail_({label:"AdGroup "+adGroupId});this.currentView_=this.adGroupView_;this.renderAdGroup_(adGroupId)};
google.ads.adwords.objstatsext.UIManager.prototype.renderAdGroup_=function(adGroupId){if(this.adGroupView_.loading)return;if(!adGroupId)if(this.adGroupView_.adGroup)adGroupId=this.adGroupView_.adGroup.id;else return;this.switchToStats();this.adGroupView_.loading=true;this.awApiLoader_.getAdGroup(adGroupId,goog.bind(function(adGroup){this.adGroupView_.adGroup=adGroup;$("#adGroupName").text(adGroup.name);$("#adGroupBid").text(adGroup.bid);$("#adGroupClicks").text(adGroup.stats.clicks);$("#adGroupImpressions").text(adGroup.stats.impressions);
$("#adGroupCost").text(adGroup.stats.cost.value);$("#adGroupConversions").text(adGroup.stats.conversions)},this),goog.bind(this.handleError_,this));this.adGroupView_.dataTableViews.adsDataTable.dataAdapterGet=goog.bind(this.awApiLoader_.getAds,this.awApiLoader_,adGroupId);this.updateDataTable_(this.adGroupView_,this.adGroupView_.dataTableViews.adsDataTable);this.adGroupView_.dataTableViews.criteriaDataTable.dataAdapterGet=goog.bind(this.awApiLoader_.getCriteria,this.awApiLoader_,adGroupId);this.updateDataTable_(this.adGroupView_,
this.adGroupView_.dataTableViews.criteriaDataTable)};
google.ads.adwords.objstatsext.UIManager.prototype.renderAdsGraph_=function(ads){if(google.visualization&&google.visualization.DataTable){var data=new google.visualization.DataTable;data.addColumn("string","Ad");data.addColumn("number","Imp.");data.addColumn("number","Clicks");data.addColumn("number","Conv.");data.addColumn("number","Cost");data.addColumn("number","Avg. Pos.");data.addRows(ads.length);for(var j=0;j<ads.length;++j){data.setValue(j,0,ads[j].typeTitle);data.setValue(j,1,ads[j].stats.impressions);
data.setValue(j,2,ads[j].stats.clicks);data.setValue(j,3,ads[j].stats.conversions);data.setValue(j,4,ads[j].stats.cost.value);data.setValue(j,5,ads[j].stats.averagePosition)}(new google.visualization.BarChart(document.getElementById("adsGraph"))).draw(data,{title:"Ad Statistics",width:440,height:270,hAxis:{logScale:true,minValue:0}})}else this.showGraphUnavailableError_(document.getElementById("adsGraph"))};
google.ads.adwords.objstatsext.UIManager.prototype.renderCriteriaGraph_=function(criteria){if(google.visualization&&google.visualization.DataTable){var data=new google.visualization.DataTable;data.addColumn("string","Criteria");data.addColumn("number","Imp.");data.addColumn("number","Clicks");data.addColumn("number","Conv.");data.addRows(criteria.length);for(var j=0;j<criteria.length;++j){data.setValue(j,0,criteria[j].typeTitle);data.setValue(j,1,criteria[j].stats.impressions);data.setValue(j,2,criteria[j].stats.clicks);
data.setValue(j,3,criteria[j].stats.conversions)}(new google.visualization.BarChart(document.getElementById("criteriaGraph"))).draw(data,{title:"Criteria Statistics",width:440,height:270,hAxis:{logScale:true}})}else this.showGraphUnavailableError_(document.getElementById("criteriaGraph"))};google.ads.adwords.objstatsext.UIManager.prototype.nextAds=function(){this.adGroupView_.dataTableViews.adsDataTable.page++;this.renderAdGroup_()};
google.ads.adwords.objstatsext.UIManager.prototype.previousAds=function(){if(this.adGroupView_.dataTableViews.adsDataTable.page==1)return;this.adGroupView_.dataTableViews.adsDataTable.page--;this.renderAdGroup_()};google.ads.adwords.objstatsext.UIManager.prototype.nextCriteria=function(){this.adGroupView_.dataTableViews.criteriaDataTable.page++;this.renderAdGroup_()};
google.ads.adwords.objstatsext.UIManager.prototype.previousCriteria=function(){if(this.adGroupView_.dataTableViews.criteriaDataTable.page==1)return;this.adGroupView_.dataTableViews.criteriaDataTable.page--;this.renderAdGroup_()};
google.ads.adwords.objstatsext.UIManager.prototype.updateDataTable_=function(view,dataTableView){var resultsTable=$(document.getElementById(dataTableView.resultsTable));var loadingView=$(document.getElementById(dataTableView.loadingView));var rowTemplate=$(document.getElementById(dataTableView.dataRowTemplate));var paginationSection=$(document.getElementById(dataTableView.paginationSection));var countersSection=$(document.getElementById(dataTableView.countersSection));var previousLink=$(document.getElementById(dataTableView.previousLink));
var nextLink=$(document.getElementById(dataTableView.nextLink));resultsTable.hide();loadingView.show();paginationSection.hide();var offset=this.calculateOffset_(dataTableView);var resultsHandler=goog.bind(function(data){dataTableView.data=data;resultsTable.empty();rowTemplate.tmpl(data.entries).appendTo(resultsTable);loadingView.hide();this.updateTableCounters_(data,dataTableView,countersSection,previousLink,nextLink);resultsTable.show();paginationSection.show();view.loading=false;var rendererFn=
goog.bind(dataTableView.graphRenderer,this,data.entries);setTimeout(rendererFn,100)},this);var errorsHandler=goog.bind(this.handleError_,this);dataTableView.dataAdapterGet(offset,this.PER_PAGE_,resultsHandler,errorsHandler)};
google.ads.adwords.objstatsext.UIManager.prototype.updateTableCounters_=function(results,viewState,counters,previous,next){var first=this.calculateOffset_(viewState);var last=first+this.PER_PAGE_>results.totalNumEntries?results.totalNumEntries:first+this.PER_PAGE_;first++;counters.empty();$("#countersTemplate").tmpl({first:first,last:last,total:results.totalNumEntries}).appendTo(counters);previous.hide();next.hide();if(viewState.page>1)previous.show();if(last<results.totalNumEntries)next.show()};
google.ads.adwords.objstatsext.UIManager.prototype.pushToCrumbtrail_=function(elem){this.crumbtrailElements_.push(elem);this.renderCrumbtrail()};google.ads.adwords.objstatsext.UIManager.prototype.popFromCrumbtrail_=function(){if(this.crumbtrailElements_.length==1)return;this.crumbtrailElements_.pop();this.renderCrumbtrail()};
google.ads.adwords.objstatsext.UIManager.prototype.renderCrumbtrail=function(){var htmlCode="";for(var i=0,len=this.crumbtrailElements_.length;i<len;i++){var crumbTrailElement=this.crumbtrailElements_[i].label;if(i<len-1&&this.crumbtrailElements_[i].action)crumbTrailElement='<a href="javascript:'+this.crumbtrailElements_[i].action+'">'+crumbTrailElement+"</a>";htmlCode+=(i!=0?" &gt; ":"")+crumbTrailElement}$("#crumbtrail").html(htmlCode)};
google.ads.adwords.objstatsext.UIManager.prototype.switchToGraph=function(){this.currentView_.viewState=this.GRAPH_VIEW;switch(this.currentView_.viewName){case this.ALL_CAMPAIGNS_VIEW:this.transition_("#campaignsTable","#campaignsGraph");break;case this.CAMPAIGN_VIEW:this.transition_("#adGroupsTable","#adGroupsGraph");break;case this.AD_GROUP_VIEW:this.transition_("#adsTable","#adsGraph");this.transition_("#criteriaTable","#criteriaGraph");break}};
google.ads.adwords.objstatsext.UIManager.prototype.switchToStats=function(){this.currentView_.viewState=this.STATS_VIEW;switch(this.currentView_.viewName){case this.ALL_CAMPAIGNS_VIEW:this.transition_("#campaignsGraph","#campaignsTable");break;case this.CAMPAIGN_VIEW:this.transition_("#adGroupsGraph","#adGroupsTable");break;case this.AD_GROUP_VIEW:this.transition_("#adsGraph","#adsTable");this.transition_("#criteriaGraph","#criteriaTable");break}};
google.ads.adwords.objstatsext.UIManager.prototype.transition_=function(section1,section2){$(section2).show();$(section1).animate({opacity:0},this.VIEW_ANIMATION_DELAY,"linear",function(){$(section1).hide()});$(section2).animate({opacity:1},this.VIEW_ANIMATION_DELAY)};
google.ads.adwords.objstatsext.UIManager.prototype.handleError_=function(exception){this.currentView_.loading=false;$("#extensionBody").hide();if(exception.getInnerException()instanceof google.ads.common.AuthTokenException){$("#settingAlerts").show();$("#settingsErrorAlert").show();$("#settingsErrorMessage").html(exception.getMessage())}else{$("#errors").show();$("#generalErrorAlert").show();$("#generalErrorDetail").hide();exception=exception.getApiException()?exception.getApiException():exception;
$("#generalErrorMessage").html(exception.getMessage());if(exception.getDetail()){$("#generalErrorDetail").html(exception.getDetail());$("#generalErrorDetail").show()}}};google.ads.adwords.objstatsext.UIManager.prototype.closeError_=function(){window.location.reload(1)};google.ads.adwords.objstatsext.UIManager.prototype.showGraphUnavailableError_=function(errorArea){$(errorArea).text("");$(errorArea).html('<div class="graphUnavailableError">'+"Graphs are unavailable, try reloading the extension.</div>")};
google.ads.adwords.objstatsext.UIManager.prototype.openSettings=function(){chrome.tabs.create({url:chrome.extension.getURL("options.html")})};google.ads.adwords.objstatsext.UIManager.prototype.calculateOffset_=function(tableViewState){return(tableViewState.page-1)*this.PER_PAGE_};
google.ads.adwords.objstatsext.UIManager.prototype.dateChanged_=function(){var fromDate=$("#fromDate").datepicker("getDate");var toDate=$("#toDate").datepicker("getDate");var datesChanged=false;if(fromDate.getTime()>toDate.getTime()){$("#fromDate").val(this.formatDate_(this.fromDate));$("#toDate").val(this.formatDate_(this.toDate))}else{if(fromDate&&fromDate.getTime()!=this.fromDate.getTime()){this.fromDate=fromDate;datesChanged=true}else $("#fromDate").val(this.formatDate_(this.fromDate));if(toDate&&
toDate.getTime()!=this.toDate.getTime()){this.toDate=toDate;datesChanged=true}else $("#toDate").val(this.formatDate_(this.toDate))}if(datesChanged){this.awApiLoader_.statsStartDate=this.fromDate;this.awApiLoader_.statsEndDate=this.toDate;switch(this.currentView_.viewName){case this.ALL_CAMPAIGNS_VIEW:this.renderAllCampaigns_();break;case this.CAMPAIGN_VIEW:this.renderCampaign_();break;case this.AD_GROUP_VIEW:this.renderAdGroup_();break}}};
google.ads.adwords.objstatsext.UIManager.prototype.getToday_=function(){var date=new Date;date.setHours(0,0,0,0);return date};google.ads.adwords.objstatsext.UIManager.prototype.formatDate_=function(date){return $.datepicker.formatDate("mm/dd/yy",date)};google.ads.adwords.objstatsext.UIManager.prototype.parseDate_=function(dateStr){return $.datepicker.parseDate("mm/dd/yy",dateStr)};
